### ISSUE TITLE
missing function createLowerLimbJoints

### ISSUE THREAD

**Issue by vuvietbach** [modenaxe/paper-auto-lowerlimb-models#4]
Correct me if I'm wrong but when I run createAutomaticOsimModels script, Matlab display error Unrecognized function or variable 'createLowerLimbJoints'. Where can I find this function?

**Comment by modenaxe** [comment]
hello, the function is in the repository, [here](https://github.com/modenaxe/msk-STAPLE/blob/3f2f2761f7442d2e7832b8083fb1915d071049b6/STAPLE/opensim/createLowerLimbJoints.m). 
Have you downloaded the git submodule as detailed in the README (Requirements section)?
I hope this helps,
Luca

**Comment by vuvietbach** [comment]
Thank you, I did not find it because I did downloaded msk staple but it was the main branch and in the main branch 'createLowerLimbJoints' function may be 'createOpensimModelJoints' ?. Anyway, it is my mistake, I will follow instructions closely next time. Thank you.

**Comment by vuvietbach** [comment]
Thanks for your answer. I am interested in including muscle in the
resulting model. Would it be possible for you to send me the instructions
about how to do it? I would appreciate it because as a third-year student
majoring in Computer Science, I don't have much experience creating
subject-specific models. I am looking forward to hearing from you.
Best regards
Bach

**Comment by modenaxe** [comment]
Adding muscles is not trivial at this stage of development, although I am working on it. I suggest you reading [this paper](https://www.sciencedirect.com/science/article/pii/S0021929018302288?via%3Dihub) and the step-by-step guide that is available in [the supplementary material](https://figshare.shef.ac.uk/articles/dataset/Data_for_paper_Investigation_of_the_dependence_of_joint_contact_forces_on_musculotendon_parameters_using_a_codified_workflow_for_image-based_modelling_/5863422). It will at least give you an idea of what needs to be done in terms of sequence of operations.
I hope this help,
Luca

**Comment by vuvietbach** [comment]
Thank you for your timely response. I did follow your workflow mentioned in
your 2018 paper, and it helped me a lot. However, I find the process too
manual. I guess for the time being, there is no other option.
Best regards,
Bach
